version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/AWS_test
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 1000
      runas: root
file_exists_behavior: OVERWRITE