version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws_test
hooks:
  ApplicationStart:
    - location: ""
      timeout: 300
      runas: root
      commands:
        - echo "Starting Django application..."
        - apt-get install -y python3-pip
        - pip3 install django whitenoise openpyxl djangorestframework
        - cd /home/ubuntu/aws_test
        - npm install
        - npm run build
        - python3 manage.py runserver 0.0.0.0:8000 &