version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.16.1
      python: 3.10
    commands:
      - apt-get install -y python3-pip
      - pip3 install django whitenoise openpyxl djangorestframework
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Packaging all files for deployment..."
      - zip -r AWS_test.zip ./*
artifacts:
  files:
    - AWS_test.zip
  discard-paths: yes